CREATE TABLE `mdb_sc1984h`.`comp1678_user` 
( `ID` INT NOT NULL AUTO_INCREMENT , `SCREEN_NAME` VARCHAR(128) NOT NULL ,
`USERNAME` VARCHAR(128) NOT NULL , `PASSWORD` VARCHAR(128) NOT NULL , 
`DTCREATION` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
PRIMARY KEY (`ID`), 
UNIQUE `user_screen_idx` (`SCREEN_NAME`), 
UNIQUE `user_username_idx` (`USERNAME`)) 
ENGINE = InnoDB;